service: trabalho-final
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 300
  iam:
    role: !Sub arn:aws:iam::${aws:accountId}:role/LabRole
  eventBridge:
    useCloudFormation: true
  environment:
    sqs_url: !Sub https://sqs.us-east-1.amazonaws.com/${aws:accountId}/espera-entrega


functions:
  sourcepizza:
    handler: handler.sourceHandlerpizza
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:${aws:accountId}:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
  detailpizza:
    handler: handler.detailHandlerpizza
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:${aws:accountId}:event-bus/pizzaria
          pattern:
            source: 
              - com.pizza.status
            detail-type: 
              - Alteracao Pizza
            detail:
              status:
                - pronto
  consumerpizza:
    handler: handler.consumerHandlerpizza
