service: event-filter

frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  iam:
    role: !Sub arn:aws:iam::565314625672:role/LabRole
  eventBridge:
    useCloudFormation: true

functions:
  source:
    handler: handler.sourceHandler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:565314625672:event-bus/Orders
          pattern:
            source:
              - com.aws.orders
  detail:
    handler: handler.detailHandler
    events:
      - eventBridge:
        eventBus:
          - arn:aws:events:us-east-1:565314625672:event-bus/Orders
        pattern:
          source:
            - com.aws.orders
          detail-type:
            - Order Notification
          detail:
            location:
              - eu-west